### ISSUE TITLE
when the pre-trained model going to be launched?

### ISSUE THREAD

**Issue by harshbhatt7585** [NerdFNY/PGVTON#1]

**Comment by harshbhatt7585** [comment]
Hii, when the inference code and pre-trained model you are launching?

**Comment by NerdFNY** [comment]
> Hii, when the inference code and pre-trained model you are launching?

Hi, thank your appreciation of our work. Since our manuscript is still in peer review, we will release our code after acceptance as soon as possible.

**Comment by harshbhatt7585** [comment]
Thank you for the update.

**Comment by Erickrus** [comment]
I'd wish you could have a notebook to run through. 
Importantly, provide a requirements.txt with main package version e.g. torch.
waiting for your pretrained model

Many thanks

```shell
!git clone https://github.com/NerdFNY/PGVTON
!pip3 install -q -r /content/PGVTON/requirment.txt
!pip3 install -U gdown
!gdown 1MxCUvKxejnwWnoZ-KoCyMCXo3TLhRuTo
!tar -xzvf viton_resize.tar.gz > /dev/null


%cd /content/PGVTON
TEST_DIR="/content/viton_resize/test"
!python main.py --data_dir {TEST_DIR} --mode eval --submodel TPIM 
!python main.py --data_dir {TEST_DIR} --mode eval --submodel PTM 
!python main.py --data_dir {TEST_DIR} --mode eval --submodel RSIM 
!python composition.py
```
